// const parseMap = require('../parser.js');
// // planet of stress tset
// // dev planet; never meant to be seen in the game

// const text = `
// {"arena":{"width":10000,"height":10000},"enemy":[],"safes":[],"spawns":[],"playerSpawn":{"x":750,"y":3700},"name":"PoST","longName":"Planet of Stress Test","tileColor":"#383838","bgColor":"#0d0d0d","safeColor":"#8c8c8c","difficulty":"Cataclysmic","renderRaycasting":false,"texts":[{"x":1575,"y":2775,"w":25,"h":25,"size":30,"text":"DANGER ZONE","angle":0,"story":false},{"x":350,"y":2825,"w":25,"h":25,"size":30,"text":"DANGER ZONE","angle":0,"story":false},{"x":1025,"y":3075,"w":25,"h":25,"size":30,"text":"DANGER ZONE (If u go up the 10k+ obstacles will render)","angle":0,"story":false},{"x":2275,"y":3000,"w":25,"h":25,"size":30,"text":"DANGER ZONE","angle":0,"story":false},{"x":2000,"y":2425,"w":25,"h":25,"size":30,"text":"DANGER ZONE","angle":0,"story":false},{"x":2325,"y":2100,"w":25,"h":25,"size":30,"text":"DANGER ZONE","angle":0,"story":false},{"x":2025,"y":1525,"w":25,"h":25,"size":30,"text":"DANGER ZONE","angle":0,"story":false},{"x":2325,"y":925,"w":25,"h":25,"size":30,"text":"DANGER ZONE","angle":0,"story":false},{"x":2000,"y":475,"w":25,"h":25,"size":30,"text":"DANGER ZONE","angle":0,"story":false},{"x":2250,"y":75,"w":25,"h":25,"size":30,"text":"DANGER ZONE","angle":0,"story":false}],"obstacles":[{"type":"normal","x":-225,"y":1700,"w":2375,"h":1525,"canJump":true,"angle":0},{"type":"normal","x":1350,"y":-225,"w":1200,"h":3450,"canJump":true,"angle":0}]}
// `

// const {
//     TransObstacle,
//     NormalObstacle,
//     BouncyObstacle,
//     CircularNormalObstacle,
//     CircularBouncyObstacle,
//     RotatingNormal,
//     Lava,
//     RotatingLava,
//     CircularLavaObstacle,
//     SpeedObstacle,
//     GravObstacle,
//     Air,
//     Polygon,
//     Tp,
//     MovingObstacle,
//     StoryDisplay,
//     Pusher,
//     Sentry,
//     Camera,
//     Pushbox,
//     Deathcure,
//     CircularSafeObstacle,
//     Zone,
//     Deathmark,
//     MovingLavaObstacle,
//     CircularCoin,
//     Portal,
//     Winpad,
//     Booster,
//     WallBooster,
//     WB,
//     SpeedTrap,
//     GrowingObstacle,
//     GrowingLavaObstacle,
//     GrowingCircleObstacle,
//     GrowingCircleLavaObstacle,
//     SizePlayer,
//     Slip,
//     BoostPad,
//     Tornado,
//     SnapGrid,
//     VinetteIncrease,
//     ColorChange,
//     RotatingTp,
//     PlatformerGrav,
//     MovingSafe,
//     RotatingSafe,
//     BreakableObstacle,
//     SwitchLava,
//     SwitchObstacle,
//     TimeTrap,
//     InvincibilityPowerup,
//     Filter,
//     Particles,
//     MovingSpeedTrap,
//     RotatingSpeedTrap,
//     DeadMove,
//     Revive,
//     DrawObstacle,
//     Clone,
//     Ship,
//     CoinDoor,
//     MusicChange,
//     Redirect,
//     CookieCheck,
//     Typing,
//     RevivePowerup,
//     Raycasting,
//     Spring,
//     CircularSnap,
//     IDIT,
//     CameraChange,
//     Gun,
//     Mashing,
//     Golf,
//     Zoom,
//     RestrictAxis,
//     Custom,
//     FallingArrow,
//     CircularHollowObstacle,
//     SwitchGrav,
//     Door,
//     Button,
//     CircularDoor,
//     ReusableButton,
//     TimeButton,
//     TimeTrapButton,
//     LavaDoor,
//     Invert,
//     DragonPowerup,
//     PlayerCollide,
//     CrowdButton,
//     Hole,
//     GunslingerPowerup,
//     AmogusPowerup,
//     Demo,
//     EnemyButton,
//     CircularSliceObstacle,
//     CircularHollowSlice,
//     RoundedCorners,
//     RoundedLava,
//     GrapplePowerup,
//     GrapplePoint,
//     CircularHollowLava,
//     CircularLavaSlice,
//     CircularHollowLavaSlice,
//     ResetCoins,
//     Bezier,
//     BoxButton,
//     RotatingPause,
//     RotatingLavaPause,
//     MovingPause,
//     MovingLavaPause,
//     FrictionChanger,
//     MovingGrapplePoint,
//     Oval,
//     LavaOval,
//     EnemyEffector,
//     EnemyTp,
//     EnemyWall,
//     EnemyPolyWall,
//     EnemyPolyTp,
//     CircularHollowSliceEnemyWall,
//     CircularHollowSliceEnemyTp,
//     Mirror,
//     Rail,
//     TpTrap,
//     DeadPusher,
//     Bonus,
//     CircularBonus,ZMode,
//     IFramePlayer, MorphButton,MorphObstacle,MorphButtonTimed,MorphMoving,MorphLavaMove,DirNormal,PushboxResetButton,MorphMoveReset,
//     ResetTimeTraps,
//     NoRespawn,
//     RotateCanvas,
//     ForceInput,
// } = require('../obstacle.js');

// let map = parseMap(text);
// let { obstacles, spawns } = map;
// for(let i = 0; i < 10000; i++){
//     obstacles.push(new NormalObstacle(50,50,100,100));
// }
	  
// module.exports = map;